---
#Mariadb configuration for Nextcloud
- name: Creates database for NextCloud
  mysql_db:
    name: "{{ ncDBName }}"
    state: present
    login_user: root
    login_password: "{{ mysqlRootPassword }}"
  tags: [ mysql ]

- name: Create MySQL user for NextCloud
  mysql_user:
    name: "{{ ncDBUser }}"
    password: "{{ ncDBPassword }}"
    priv: "{{ ncDBName }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysqlRootPassword }}"
  tags: [ mysql ]

# Configuración de Apache
- name: Create document root
  file:
    path: "/var/www/{{ ncDomain }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'
  tags: [ apache ]

- name: Set up Apache VirtualHost
  template:
    src: "../files/ncApache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ ncVirtualHostFile }}"
  tags: [ apache ]

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ ncVirtualHostFile }}
  tags: [ apache ]

- name: Restart Apache to apply changes
  service:
    name: apache2
    state: restarted
  tags: [ apache ]
#Instalar Nextcloud

- name: Install unzip
  apt: 
    name: "unzip"
    update_cache: yes
    state: latest
  ags: [ system ]

- name: Download and unpack latest nextcloud
  unarchive:
    src: https://download.nextcloud.com/server/releases/latest.zip
    dest: "/var/www/{{ ncdomain }}"
    remote_src: yes
    creates: "/var/www/{{ ncDomain }}/nextcloud"
  tags: [ nextcloud ]

- name: Set ownership
  file:
    path: "/var/www/{{ ncDomain }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  tags: [ nextcloud ]

